version: '3.8'
services:
  backend:
    image: my_backend_image
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
    networks:
      - my_network

  frontend:
    image: my_frontend_image
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge